In [1]:
#import necessary libraries in conventional format'
#hint: we might need numpy as well!
import pandas as pd
import numpy as np

We would largely focus on dataframes here. To better understand we would use a real-life dataset

In [2]:
#read data that is stores in datasets/black-friday folder
data=pd.read_csv('../datasets/black-friday/BlackFriday.csv')

In [3]:
#print shape of dataframe
data.shape

(537577, 12)

In [4]:
#view the name os all columns
data.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [5]:
#Using iloc print the rows from 4 to 40000
data.iloc[4:40000,]

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,NaN,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,NaN,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,NaN,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,NaN,NaN,7871
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,NaN,5254
11,1000005,P00014542,M,26-35,20,A,1,1,8,NaN,NaN,3957
12,1000005,P00031342,M,26-35,20,A,1,1,8,NaN,NaN,6073
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.0,15665
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.0,5378
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,NaN,2079
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.0,13055
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,NaN,8851
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.0,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.0,19614
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.0,NaN,8584
21,1000008,P00156442,M,26-35,12,C,4+,1,8,NaN,NaN,9872
22,1000008,P00213742,M,26-35,12,C,4+,1,8,NaN,NaN,9743
23,1000008,P00214442,M,26-35,12,C,4+,1,8,NaN,NaN,5982
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.0,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,NaN,16662
26,1000009,P00039942,M,26-35,17,C,0,0,8,NaN,NaN,5887
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.0,NaN,6973
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.0,14.0,5391
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.0,16352
30,1000010,P00118742,F,36-45,1,B,4+,1,5,11.0,NaN,8886
31,1000010,P00297942,F,36-45,1,B,4+,1,8,NaN,NaN,5875
32,1000010,P00266842,F,36-45,1,B,4+,1,5,NaN,NaN,8854
33,1000010,P00058342,F,36-45,1,B,4+,1,3,4.0,NaN,10946
...,...,...,...,...,...,...,...,...,...,...,...,...
39970,1000149,P00136842,M,26-35,1,B,2,1,1,8.0,16.0,15328
39971,1000149,P00145642,M,26-35,1,B,2,1,1,8.0,17.0,11539
39972,1000149,P00303442,M,26-35,1,B,2,1,1,8.0,14.0,15308
39973,1000149,P00037042,M,26-35,1,B,2,1,1,15.0,NaN,11792
39974,1000149,P00219242,M,26-35,1,B,2,1,4,5.0,NaN,2846
39975,1000149,P00300042,M,26-35,1,B,2,1,16,NaN,NaN,12420
39976,1000149,P00248342,M,26-35,1,B,2,1,8,13.0,NaN,9815
39977,1000149,P00038242,M,26-35,1,B,2,1,6,8.0,NaN,12552
39978,1000150,P00334242,M,36-45,7,B,0,1,1,8.0,NaN,19033
39979,1000150,P00275642,M,36-45,7,B,0,1,8,NaN,NaN,8143
39980,1000150,P00150542,M,36-45,7,B,0,1,5,NaN,NaN,8674
39981,1000150,P00192842,M,36-45,7,B,0,1,5,14.0,NaN,5235
39982,1000150,P00324942,M,36-45,7,B,0,1,5,NaN,NaN,6887
39983,1000150,P00326642,M,36-45,7,B,0,1,8,NaN,NaN,9759
39984,1000151,P00196042,F,26-35,20,A,1,1,4,9.0,15.0,2806
39985,1000151,P00183242,F,26-35,20,A,1,1,5,15.0,NaN,5161
39986,1000151,P00334242,F,26-35,20,A,1,1,1,8.0,NaN,19459
39987,1000151,P00036842,F,26-35,20,A,1,1,1,14.0,16.0,8318
39988,1000151,P00130842,F,26-35,20,A,1,1,5,14.0,NaN,3582
39989,1000151,P00045542,F,26-35,20,A,1,1,5,14.0,NaN,5176
39990,1000151,P00021842,F,26-35,20,A,1,1,5,8.0,14.0,6988
39991,1000151,P00008042,F,26-35,20,A,1,1,6,8.0,14.0,20006
39992,1000151,P00059142,F,26-35,20,A,1,1,8,14.0,NaN,4055
39993,1000151,P00156442,F,26-35,20,A,1,1,8,NaN,NaN,10074
39994,1000151,P00150542,F,26-35,20,A,1,1,5,NaN,NaN,8615
39995,1000151,P00112742,F,26-35,20,A,1,1,2,14.0,NaN,13184
39996,1000151,P00139942,F,26-35,20,A,1,1,5,NaN,NaN,8866
39997,1000151,P00054942,F,26-35,20,A,1,1,5,8.0,NaN,6965
39998,1000151,P00227142,F,26-35,20,A,1,1,5,NaN,NaN,5206
39999,1000151,P00358342,F,26-35,20,A,1,1,11,15.0,16.0,3184

In [6]:
#USing iloc print all rows but only 'product_id' column 
data.iloc[:,1]

0         P00069042
1         P00248942
2         P00087842
3         P00085442
4         P00285442
5         P00193542
6         P00184942
7         P00346142
8          P0097242
9         P00274942
10        P00251242
11        P00014542
12        P00031342
13        P00145042
14        P00231342
15        P00190242
16         P0096642
17        P00058442
18        P00036842
19        P00249542
20        P00220442
21        P00156442
22        P00213742
23        P00214442
24        P00303442
25        P00135742
26        P00039942
27        P00161442
28        P00078742
29        P00085942
            ...
537547    P00244042
537548    P00111042
537549    P00345842
537550    P00278242
537551    P00313442
537552     P0098642
537553    P00119342
537554    P00114042
537555    P00135142
537556    P00194542
537557    P00175242
537558    P00101942
537559    P00109142
537560    P00084842
537561    P00078142
537562    P00146742
537563    P00154642
537564    P00117442
537565    P00051142
537566    P00048742
537567    P00157542
537568    P00250642
537569    P00023142
537570    P00162442
537571    P00221442
537572    P00193542
537573    P00111142
537574    P00345942
537575    P00285842
537576    P00118242
Name: Product_ID, Length: 537577, dtype: object

In [7]:
#print all data from row with columns reversed
data.iloc[:,::-1]

,Purchase,Product_Category_3,Product_Category_2,Product_Category_1,Marital_Status,Stay_In_Current_City_Years,City_Category,Occupation,Age,Gender,Product_ID,User_ID
0,8370,NaN,NaN,3,0,2,A,10,0-17,F,P00069042,1000001
1,15200,14.0,6.0,1,0,2,A,10,0-17,F,P00248942,1000001
2,1422,NaN,NaN,12,0,2,A,10,0-17,F,P00087842,1000001
3,1057,NaN,14.0,12,0,2,A,10,0-17,F,P00085442,1000001
4,7969,NaN,NaN,8,0,4+,C,16,55+,M,P00285442,1000002
5,15227,NaN,2.0,1,0,3,A,15,26-35,M,P00193542,1000003
6,19215,17.0,8.0,1,1,2,B,7,46-50,M,P00184942,1000004
7,15854,NaN,15.0,1,1,2,B,7,46-50,M,P00346142,1000004
8,15686,NaN,16.0,1,1,2,B,7,46-50,M,P0097242,1000004
9,7871,NaN,NaN,8,1,1,A,20,26-35,M,P00274942,1000005
10,5254,NaN,11.0,5,1,1,A,20,26-35,M,P00251242,1000005
11,3957,NaN,NaN,8,1,1,A,20,26-35,M,P00014542,1000005
12,6073,NaN,NaN,8,1,1,A,20,26-35,M,P00031342,1000005
13,15665,5.0,2.0,1,1,1,A,20,26-35,M,P00145042,1000005
14,5378,14.0,8.0,5,0,1,A,9,51-55,F,P00231342,1000006
15,2079,NaN,5.0,4,0,1,A,9,51-55,F,P00190242,1000006
16,13055,4.0,3.0,2,0,1,A,9,51-55,F,P0096642,1000006
17,8851,NaN,14.0,5,0,1,A,9,51-55,F,P00058442,1000006
18,11788,16.0,14.0,1,1,1,B,1,36-45,M,P00036842,1000007
19,19614,15.0,5.0,1,1,4+,C,12,26-35,M,P00249542,1000008
20,8584,NaN,14.0,5,1,4+,C,12,26-35,M,P00220442,1000008
21,9872,NaN,NaN,8,1,4+,C,12,26-35,M,P00156442,1000008
22,9743,NaN,NaN,8,1,4+,C,12,26-35,M,P00213742,1000008
23,5982,NaN,NaN,8,1,4+,C,12,26-35,M,P00214442,1000008
24,11927,14.0,8.0,1,1,4+,C,12,26-35,M,P00303442,1000008
25,16662,NaN,8.0,6,0,0,C,17,26-35,M,P00135742,1000009
26,5887,NaN,NaN,8,0,0,C,17,26-35,M,P00039942,1000009
27,6973,NaN,14.0,5,0,0,C,17,26-35,M,P00161442,1000009
28,5391,14.0,8.0,5,0,0,C,17,26-35,M,P00078742,1000009
29,16352,8.0,4.0,2,1,4+,B,1,36-45,F,P00085942,1000010
...,...,...,...,...,...,...,...,...,...,...,...,...
537547,11543,15.0,2.0,1,0,1,C,18,18-25,M,P00244042,1004733
537548,20924,NaN,NaN,15,1,1,B,1,51-55,M,P00111042,1004734
537549,13082,14.0,8.0,2,1,1,B,1,51-55,M,P00345842,1004734
537550,11658,NaN,NaN,1,0,3,C,3,46-50,M,P00278242,1004735
537551,6863,8.0,6.0,5,0,3,C,3,46-50,M,P00313442,1004735
537552,16415,NaN,8.0,6,0,3,C,3,46-50,M,P0098642,1004735
537553,18526,NaN,13.0,10,0,3,C,3,46-50,M,P00119342,1004735
537554,7099,NaN,14.0,5,0,3,C,3,46-50,M,P00114042,1004735
537555,578,NaN,16.0,13,0,3,C,3,46-50,M,P00135142,1004735
537556,2183,NaN,14.0,8,1,1,A,20,18-25,M,P00194542,1004736
537557,12724,NaN,NaN,2,1,1,A,20,18-25,M,P00175242,1004736
537558,7796,NaN,17.0,8,1,1,A,20,18-25,M,P00101942,1004736
537559,7770,NaN,17.0,8,1,1,A,20,18-25,M,P00109142,1004736
537560,5940,NaN,16.0,8,1,1,A,20,18-25,M,P00084842,1004736
537561,7834,NaN,16.0,8,1,1,A,20,18-25,M,P00078142,1004736
537562,11508,14.0,13.0,1,1,1,A,20,18-25,M,P00146742,1004736
537563,6074,NaN,NaN,8,1,1,A,20,18-25,M,P00154642,1004736
537564,7084,NaN,14.0,5,1,1,A,20,18-25,M,P00117442,1004736
537565,7934,NaN,NaN,8,1,1,A,20,18-25,M,P00051142,1004736
537566,5350,NaN,NaN,5,1,1,A,20,18-25,M,P00048742,1004736
537567,1994,NaN,14.0,8,1,1,A,20,18-25,M,P00157542,1004736
537568,5930,NaN,NaN,11,1,1,A,20,18-25,M,P00250642,1004736
537569,7042,NaN,14.0,5,1,1,A,20,18-25,M,P00023142,1004736
537570,15491,NaN,16.0,1,1,1,A,20,18-25,M,P00162442,1004736
537571,11852,5.0,2.0,1,0,1,C,16,36-45,M,P00221442,1004737
537572,11664,NaN,2.0,1,0,1,C,16,36-45,M,P00193542,1004737
537573,19196,16.0,15.0,1,0,1,C,16,36-45,M,P00111142,1004737
537574,8043,NaN,15.0,8,0,1,C,16,36-45,M,P00345942,1004737
537575,7172,NaN,NaN,5,0,1,C,16,36-45,M,P00285842,1004737
537576,6875,NaN,8.0,5,0,1,C,16,36-45,M,P00118242,1004737

In [8]:
#using loc print 3 to 390 rows and Gender to martial_status column
data.loc[3:390,'Gender':'Marital_Status']

,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status
3,F,0-17,10,A,2,0
4,M,55+,16,C,4+,0
5,M,26-35,15,A,3,0
6,M,46-50,7,B,2,1
7,M,46-50,7,B,2,1
8,M,46-50,7,B,2,1
9,M,26-35,20,A,1,1
10,M,26-35,20,A,1,1
11,M,26-35,20,A,1,1
12,M,26-35,20,A,1,1
13,M,26-35,20,A,1,1
14,F,51-55,9,A,1,0
15,F,51-55,9,A,1,0
16,F,51-55,9,A,1,0
17,F,51-55,9,A,1,0
18,M,36-45,1,B,1,1
19,M,26-35,12,C,4+,1
20,M,26-35,12,C,4+,1
21,M,26-35,12,C,4+,1
22,M,26-35,12,C,4+,1
23,M,26-35,12,C,4+,1
24,M,26-35,12,C,4+,1
25,M,26-35,17,C,0,0
26,M,26-35,17,C,0,0
27,M,26-35,17,C,0,0
28,M,26-35,17,C,0,0
29,F,36-45,1,B,4+,1
30,F,36-45,1,B,4+,1
31,F,36-45,1,B,4+,1
32,F,36-45,1,B,4+,1
...,...,...,...,...,...,...
361,F,51-55,1,B,4+,1
362,F,51-55,1,B,4+,1
363,F,51-55,1,B,4+,1
364,F,51-55,1,B,4+,1
365,F,51-55,1,B,4+,1
366,F,51-55,1,B,4+,1
367,F,51-55,1,B,4+,1
368,F,51-55,1,B,4+,1
369,F,51-55,1,B,4+,1
370,M,51-55,1,C,1,1
371,M,51-55,1,C,1,1
372,M,26-35,17,C,1,0
373,F,36-45,3,A,1,0
374,F,36-45,3,A,1,0
375,F,36-45,3,A,1,0
376,F,36-45,3,A,1,0
377,F,36-45,3,A,1,0
378,F,36-45,3,A,1,0
379,F,36-45,3,A,1,0
380,F,36-45,3,A,1,0
381,F,36-45,3,A,1,0
382,F,36-45,3,A,1,0
383,F,36-45,3,A,1,0
384,F,36-45,3,A,1,0
385,F,36-45,3,A,1,0
386,F,36-45,3,A,1,0
387,F,36-45,3,A,1,0
388,M,18-25,4,C,2,0
389,M,18-25,4,C,2,0
390,M,18-25,4,C,2,0

In [9]:
#using slice operator reverse all rows
data.loc[::-1,:]

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
537576,1004737,P00118242,M,36-45,16,C,1,0,5,8.0,NaN,6875
537575,1004737,P00285842,M,36-45,16,C,1,0,5,NaN,NaN,7172
537574,1004737,P00345942,M,36-45,16,C,1,0,8,15.0,NaN,8043
537573,1004737,P00111142,M,36-45,16,C,1,0,1,15.0,16.0,19196
537572,1004737,P00193542,M,36-45,16,C,1,0,1,2.0,NaN,11664
537571,1004737,P00221442,M,36-45,16,C,1,0,1,2.0,5.0,11852
537570,1004736,P00162442,M,18-25,20,A,1,1,1,16.0,NaN,15491
537569,1004736,P00023142,M,18-25,20,A,1,1,5,14.0,NaN,7042
537568,1004736,P00250642,M,18-25,20,A,1,1,11,NaN,NaN,5930
537567,1004736,P00157542,M,18-25,20,A,1,1,8,14.0,NaN,1994
537566,1004736,P00048742,M,18-25,20,A,1,1,5,NaN,NaN,5350
537565,1004736,P00051142,M,18-25,20,A,1,1,8,NaN,NaN,7934
537564,1004736,P00117442,M,18-25,20,A,1,1,5,14.0,NaN,7084
537563,1004736,P00154642,M,18-25,20,A,1,1,8,NaN,NaN,6074
537562,1004736,P00146742,M,18-25,20,A,1,1,1,13.0,14.0,11508
537561,1004736,P00078142,M,18-25,20,A,1,1,8,16.0,NaN,7834
537560,1004736,P00084842,M,18-25,20,A,1,1,8,16.0,NaN,5940
537559,1004736,P00109142,M,18-25,20,A,1,1,8,17.0,NaN,7770
537558,1004736,P00101942,M,18-25,20,A,1,1,8,17.0,NaN,7796
537557,1004736,P00175242,M,18-25,20,A,1,1,2,NaN,NaN,12724
537556,1004736,P00194542,M,18-25,20,A,1,1,8,14.0,NaN,2183
537555,1004735,P00135142,M,46-50,3,C,3,0,13,16.0,NaN,578
537554,1004735,P00114042,M,46-50,3,C,3,0,5,14.0,NaN,7099
537553,1004735,P00119342,M,46-50,3,C,3,0,10,13.0,NaN,18526
537552,1004735,P0098642,M,46-50,3,C,3,0,6,8.0,NaN,16415
537551,1004735,P00313442,M,46-50,3,C,3,0,5,6.0,8.0,6863
537550,1004735,P00278242,M,46-50,3,C,3,0,1,NaN,NaN,11658
537549,1004734,P00345842,M,51-55,1,B,1,1,2,8.0,14.0,13082
537548,1004734,P00111042,M,51-55,1,B,1,1,15,NaN,NaN,20924
537547,1004733,P00244042,M,18-25,18,C,1,0,1,2.0,15.0,11543
...,...,...,...,...,...,...,...,...,...,...,...,...
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.0,16352
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.0,14.0,5391
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.0,NaN,6973
26,1000009,P00039942,M,26-35,17,C,0,0,8,NaN,NaN,5887
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,NaN,16662
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.0,11927
23,1000008,P00214442,M,26-35,12,C,4+,1,8,NaN,NaN,5982
22,1000008,P00213742,M,26-35,12,C,4+,1,8,NaN,NaN,9743
21,1000008,P00156442,M,26-35,12,C,4+,1,8,NaN,NaN,9872
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.0,NaN,8584
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.0,19614
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.0,11788
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,NaN,8851
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.0,13055
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,NaN,2079
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.0,5378
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.0,15665
12,1000005,P00031342,M,26-35,20,A,1,1,8,NaN,NaN,6073
11,1000005,P00014542,M,26-35,20,A,1,1,8,NaN,NaN,3957
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,NaN,5254
9,1000005,P00274942,M,26-35,20,A,1,1,8,NaN,NaN,7871
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,NaN,15686
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,NaN,15854
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,NaN,15227
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370

In [10]:
#print all data where Purchase is greater than 10000
data.loc[data['Purchase']>=10000]

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,NaN,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,NaN,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,NaN,15686
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.0,15665
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.0,13055
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.0,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.0,19614
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.0,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,NaN,16662
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.0,16352
33,1000010,P00058342,F,36-45,1,B,4+,1,3,4.0,NaN,10946
36,1000010,P00182642,F,36-45,1,B,4+,1,2,4.0,9.0,12909
38,1000010,P00155442,F,36-45,1,B,4+,1,1,11.0,15.0,15212
39,1000010,P00221342,F,36-45,1,B,4+,1,1,2.0,5.0,15705
41,1000010,P00111142,F,36-45,1,B,4+,1,1,15.0,16.0,18963
43,1000010,P0094542,F,36-45,1,B,4+,1,2,4.0,9.0,16406
44,1000010,P00148642,F,36-45,1,B,4+,1,6,10.0,13.0,12642
45,1000010,P00312142,F,36-45,1,B,4+,1,8,NaN,NaN,10007
46,1000010,P00113242,F,36-45,1,B,4+,1,1,6.0,8.0,11562
48,1000011,P00110842,F,26-35,1,C,1,0,1,2.0,5.0,19327
50,1000012,P00304242,M,26-35,12,C,2,0,1,6.0,NaN,15246
53,1000013,P00140742,M,46-50,1,C,3,1,1,15.0,NaN,15912
54,1000013,P00182342,M,46-50,1,C,3,1,1,5.0,6.0,12107
56,1000015,P00334242,M,26-35,7,A,1,0,1,8.0,NaN,19653
58,1000015,P00338442,M,26-35,7,A,1,0,1,16.0,NaN,11415
64,1000015,P00042142,M,26-35,7,A,1,0,1,2.0,6.0,11458
65,1000016,P00244242,F,36-45,0,C,0,1,1,2.0,15.0,11755
67,1000017,P00019342,M,51-55,1,C,0,0,1,6.0,15.0,15872
...,...,...,...,...,...,...,...,...,...,...,...,...
537516,1004731,P00221442,M,26-35,17,B,1,1,1,2.0,5.0,15525
537518,1004732,P00003242,M,26-35,14,B,2,1,8,15.0,NaN,10075
537519,1004732,P00345842,M,26-35,14,B,2,1,2,8.0,14.0,16469
537520,1004732,P00329542,M,26-35,14,B,2,1,1,15.0,16.0,15493
537528,1004732,P00217542,M,26-35,14,B,2,1,1,2.0,11.0,11879
537529,1004732,P00184942,M,26-35,14,B,2,1,1,8.0,17.0,19217
537530,1004732,P00318742,M,26-35,14,B,2,1,1,8.0,NaN,12086
537531,1004732,P00216242,M,26-35,14,B,2,1,3,4.0,5.0,10974
537534,1004732,P00255942,M,26-35,14,B,2,1,1,16.0,NaN,15556
537535,1004732,P00103042,M,26-35,14,B,2,1,1,14.0,NaN,15785
537536,1004732,P00005042,M,26-35,14,B,2,1,6,16.0,NaN,19933
537537,1004732,P00219942,M,26-35,14,B,2,1,6,16.0,NaN,16486
537538,1004732,P00041842,M,26-35,14,B,2,1,6,8.0,NaN,12651
537539,1004732,P00113842,M,26-35,14,B,2,1,6,8.0,16.0,12510
537540,1004732,P00124642,M,26-35,14,B,2,1,16,NaN,NaN,16610
537542,1004732,P00085242,M,26-35,14,B,2,1,8,14.0,17.0,10036
537544,1004732,P00093342,M,26-35,14,B,2,1,1,8.0,18.0,11535
537546,1004733,P00070042,M,18-25,18,C,1,0,1,2.0,16.0,15515
537547,1004733,P00244042,M,18-25,18,C,1,0,1,2.0,15.0,11543
537548,1004734,P00111042,M,51-55,1,B,1,1,15,NaN,NaN,20924
537549,1004734,P00345842,M,51-55,1,B,1,1,2,8.0,14.0,13082
537550,1004735,P00278242,M,46-50,3,C,3,0,1,NaN,NaN,11658
537552,1004735,P0098642,M,46-50,3,C,3,0,6,8.0,NaN,16415
537553,1004735,P00119342,M,46-50,3,C,3,0,10,13.0,NaN,18526
537557,1004736,P00175242,M,18-25,20,A,1,1,2,NaN,NaN,12724
537562,1004736,P00146742,M,18-25,20,A,1,1,1,13.0,14.0,11508
537570,1004736,P00162442,M,18-25,20,A,1,1,1,16.0,NaN,15491
537571,1004737,P00221442,M,36-45,16,C,1,0,1,2.0,5.0,11852
537572,1004737,P00193542,M,36-45,16,C,1,0,1,2.0,NaN,11664
537573,1004737,P00111142,M,36-45,16,C,1,0,1,15.0,16.0,19196

In [11]:
#drop the column User_id and make a new object called new_data
new_data=data.drop('User_ID',axis=1)

In [12]:
#using groupby form gender groups called grouped
grouped = data.groupby('Gender')

In [13]:
#print mean of each group by using agg function
grouped['Purchase'].agg(np.mean)

Gender
F    8809.761349
M    9504.771713
Name: Purchase, dtype: float64

In [14]:
#using a pivot table summarize purchase as mean  for index as gender and column as occupation
table = pd.pivot_table(data,values='Purchase',index=['Gender'],columns='Occupation',aggfunc=np.mean)

In [15]:
#find if there are any null values in dataset
data.isna()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,False,False,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,True,True,False
5,False,False,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,True,True,False
10,False,False,False,False,False,False,False,False,False,False,True,False
11,False,False,False,False,False,False,False,False,False,True,True,False
12,False,False,False,False,False,False,False,False,False,True,True,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,True,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,True,True,False
22,False,False,False,False,False,False,False,False,False,True,True,False
23,False,False,False,False,False,False,False,False,False,True,True,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,True,False
26,False,False,False,False,False,False,False,False,False,True,True,False
27,False,False,False,False,False,False,False,False,False,False,True,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
537547,False,False,False,False,False,False,False,False,False,False,False,False
537548,False,False,False,False,False,False,False,False,False,True,True,False
537549,False,False,False,False,False,False,False,False,False,False,False,False
537550,False,False,False,False,False,False,False,False,False,True,True,False
537551,False,False,False,False,False,False,False,False,False,False,False,False
537552,False,False,False,False,False,False,False,False,False,False,True,False
537553,False,False,False,False,False,False,False,False,False,False,True,False
537554,False,False,False,False,False,False,False,False,False,False,True,False
537555,False,False,False,False,False,False,False,False,False,False,True,False
537556,False,False,False,False,False,False,False,False,False,False,True,False
537557,False,False,False,False,False,False,False,False,False,True,True,False
537558,False,False,False,False,False,False,False,False,False,False,True,False
537559,False,False,False,False,False,False,False,False,False,False,True,False
537560,False,False,False,False,False,False,False,False,False,False,True,False
537561,False,False,False,False,False,False,False,False,False,False,True,False
537562,False,False,False,False,False,False,False,False,False,False,False,False
537563,False,False,False,False,False,False,False,False,False,True,True,False
537564,False,False,False,False,False,False,False,False,False,False,True,False
537565,False,False,False,False,False,False,False,False,False,True,True,False
537566,False,False,False,False,False,False,False,False,False,True,True,False
537567,False,False,False,False,False,False,False,False,False,False,True,False
537568,False,False,False,False,False,False,False,False,False,True,True,False
537569,False,False,False,False,False,False,False,False,False,False,True,False
537570,False,False,False,False,False,False,False,False,False,False,True,False
537571,False,False,False,False,False,False,False,False,False,False,False,False
537572,False,False,False,False,False,False,False,False,False,False,True,False
537573,False,False,False,False,False,False,False,False,False,False,False,False
537574,False,False,False,False,False,False,False,False,False,False,True,False
537575,False,False,False,False,False,False,False,False,False,True,True,False
537576,False,False,False,False,False,False,False,False,False,False,True,False

In [16]:
#fill all null values in Product_Category_2 with 0
data['Product_Category_2'].fillna(0)

0          0.0
1          6.0
2          0.0
3         14.0
4          0.0
5          2.0
6          8.0
7         15.0
8         16.0
9          0.0
10        11.0
11         0.0
12         0.0
13         2.0
14         8.0
15         5.0
16         3.0
17        14.0
18        14.0
19         5.0
20        14.0
21         0.0
22         0.0
23         0.0
24         8.0
25         8.0
26         0.0
27        14.0
28         8.0
29         4.0
          ...
537547     2.0
537548     0.0
537549     8.0
537550     0.0
537551     6.0
537552     8.0
537553    13.0
537554    14.0
537555    16.0
537556    14.0
537557     0.0
537558    17.0
537559    17.0
537560    16.0
537561    16.0
537562    13.0
537563     0.0
537564    14.0
537565     0.0
537566     0.0
537567    14.0
537568     0.0
537569    14.0
537570    16.0
537571     2.0
537572     2.0
537573    15.0
537574    15.0
537575     0.0
537576     8.0
Name: Product_Category_2, Length: 537577, dtype: float64

In [17]:
#using interpolation fill in the values of Product_Category_3
data['Product_Category_3'].interpolate()

0               NaN
1         14.000000
2         14.600000
3         15.200000
4         15.800000
5         16.400000
6         17.000000
7         15.285714
8         13.571429
9         11.857143
10        10.142857
11         8.428571
12         6.714286
13         5.000000
14        14.000000
15         9.000000
16         4.000000
17        10.000000
18        16.000000
19        15.000000
20        14.800000
21        14.600000
22        14.400000
23        14.200000
24        14.000000
25        14.000000
26        14.000000
27        14.000000
28        14.000000
29         8.000000
            ...
537547    15.000000
537548    14.500000
537549    14.000000
537550    11.000000
537551     8.000000
537552     8.545455
537553     9.090909
537554     9.636364
537555    10.181818
537556    10.727273
537557    11.272727
537558    11.818182
537559    12.363636
537560    12.909091
537561    13.454545
537562    14.000000
537563    13.000000
537564    12.000000
537565    11.000000
537566    10.000000
537567     9.000000
537568     8.000000
537569     7.000000
537570     6.000000
537571     5.000000
537572    10.500000
537573    16.000000
537574    16.000000
537575    16.000000
537576    16.000000
Name: Product_Category_3, Length: 537577, dtype: float64